// -------------------------------------------------------------------------------------------------------------------------------

// Function Task ​:   
// Write a function to generate random whole number between 0 to 10; 


function whole_number(val1=0,val2=10){
    return(Math.floor(Math.random()*(val2-(val1+1))+val1));
}
console.log("Random_Number : ", whole_number())

// Write a function which will get two parameters and return a sum of it. 

function sum(val1,val2)
{
    return val1+val2;
}
console.log("Sum of 1 and 2 : ",sum(1,2))

// Write a program to create a calculator with all arithmetic operations has functions; 

function calculator(a,b,operation)
{
    switch(operation)
    {
        case "sum":return a+b;
        case "substract":return a-b;
        case "multiply":return a*b;
        case "divide":return a/b;
        case "remainder":return a%b;
    }
}
console.log("6 * 5 = ",calculator(6,5,"multiply"));
// Do the following. 
// ● Create a function to sum two numbers and return the value. 
// ● Create a function to generate a random number between 0 to 10  
// ● Pass two values to the sum function, But first value should be passed by the user and the  second value should be generated by a random function. 

function requirement(v1)
{
    let v2=Math.floor(Math.random()*(10-1));
    return v1+v2;
}

console.log("Returned the sum of two numbers with random value : ",requirement(5))